/**
 * Authorization Roles
 */
const authRoles = {
  admin: ['SUPERADMIN'],
  staff: ['SUPERADMIN'],
  user: ['SUPERADMIN', 'USER_CIUDADANO', 'USER_EMPRESA',
    'CLI_ADMIN', 'CLI_DIRECTOR_GENERAL', 'CLI_VENTANILLA_UNICA',
    'CLI_PLANIFICACION_AMBIENTAL', 'CLI_LIQUIDADOR', 'CLI_FINANCIERO', 'CLI_JURIDICO',
    'CLI_COORDINADOR_JURIDICO', 'CLI_SUBDIRECTOR_JURIDICO', 'CLI_DIRECTOR_TERRITORIAL',
    'CLI_COORDINADOR_RECURSOS', 'CLI_PROFESIONAL_RECURSOS'
  ],
  ciudadano: [
    'SUPERADMIN', 'USER_CIUDADANO', 'USER_EMPRESA',
  ],
  corporacion: [
    'CLI_ADMIN', 'CLI_DIRECTOR_GENERAL', 'CLI_VENTANILLA_UNICA',
    'CLI_PLANIFICACION_AMBIENTAL', 'CLI_LIQUIDADOR', 'CLI_FINANCIERO', 'CLI_JURIDICO',
    'CLI_COORDINADOR_JURIDICO', 'CLI_SUBDIRECTOR_JURIDICO', 'CLI_DIRECTOR_TERRITORIAL',
    'CLI_COORDINADOR_RECURSOS', 'CLI_PROFESIONAL_RECURSOS'
  ],
  onlyGuest: [],
};

export default authRoles;
