export default {
  // baseUrl: 'http://localhost:5000/api/v1',
  baseUrl:  process.env.REACT_APP_API_URL,
  endpoints: {
    authenticate: 'authenticate',
    authenticateFunc: 'authenticate_funcionario',
    sendCodeLanding: 'sendCodeLanding',
    verifyEmail: 'verify_email',
    validar_email: 'verificar_persona_email',
    landing_auth: 'landing_auth',
    roles: 'roles',
    users: 'user',
    cities: 'cities',
    cli_clients: 'customers',
    dashboard: 'dashboard',
    state: 'states',
    procedure: 'tram_categoria',
    tramite: 'tram_tramite',
    tram_categoria_sub: 'tram_categoria_sub',
    official: 'funcionario',
    profile: 'perfil',
    changePassword: 'change_password',
    register_ciudadano: 'register_ciudadano',
    register_funcionario: 'register_funcionario',
    verificar_persona: 'verificar_persona',
    reenviar_codigo: 'enviar_codigo',
    citizen: 'ciudadano',
    tipos_documento: 'tipos_documento',
    documentacion_anexos: 'documentacion_anexos',
    solicitud: 'solicitud',
    solicitud_seven: 'solicitud_seven',
    solicitud_three: 'solicitud_three',
    etapa: 'etapa',
    etapa_uno: 'etapa_one/verificar_archivo',
    etapa_uno_devolver: 'etapa_one/devolver_doc',
    etapa_uno_aprobar: 'etapa_one/aprobar_doc',
    etapa_dos_concepto: 'etapa_one/verifcar_concepto',
    etapa_tres_liquidacion: 'etapa_one/verifcar_liquidacion',
    etapa_cuatro_pago: 'etapa_one/verifcar_pago',
  },
  url_bucket: 'https://vigpro-tramite-archives.s3.us-east-2.amazonaws.com/public',
  url_bucket_upload: 'vigpro-tramite-archives/public',
};
